# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QLabel, QMainWindow,
    QMenuBar, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QTextEdit, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(830, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.yearlyExpensesGraph = QGraphicsView(self.centralwidget)
        self.yearlyExpensesGraph.setObjectName(u"yearlyExpensesGraph")
        self.yearlyExpensesGraph.setGeometry(QRect(440, 20, 380, 240))
        self.paidOutThisWeekLabel = QLabel(self.centralwidget)
        self.paidOutThisWeekLabel.setObjectName(u"paidOutThisWeekLabel")
        self.paidOutThisWeekLabel.setGeometry(QRect(10, 90, 150, 20))
        self.remainedThisWeekLabel = QLabel(self.centralwidget)
        self.remainedThisWeekLabel.setObjectName(u"remainedThisWeekLabel")
        self.remainedThisWeekLabel.setGeometry(QRect(10, 120, 150, 20))
        self.paidOutThisWeekNum = QLabel(self.centralwidget)
        self.paidOutThisWeekNum.setObjectName(u"paidOutThisWeekNum")
        self.paidOutThisWeekNum.setGeometry(QRect(160, 90, 50, 20))
        self.remainedThisWeekNum = QLabel(self.centralwidget)
        self.remainedThisWeekNum.setObjectName(u"remainedThisWeekNum")
        self.remainedThisWeekNum.setGeometry(QRect(160, 120, 50, 20))
        self.dateLabel = QLabel(self.centralwidget)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setGeometry(QRect(10, 20, 380, 50))
        self.addExpensesTextEdit = QTextEdit(self.centralwidget)
        self.addExpensesTextEdit.setObjectName(u"addExpensesTextEdit")
        self.addExpensesTextEdit.setGeometry(QRect(190, 150, 240, 50))
        self.addExpensesTextEdit.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.addExpensesLabel = QLabel(self.centralwidget)
        self.addExpensesLabel.setObjectName(u"addExpensesLabel")
        self.addExpensesLabel.setGeometry(QRect(10, 150, 170, 20))
        self.addExpensesTextBtn = QPushButton(self.centralwidget)
        self.addExpensesTextBtn.setObjectName(u"addExpensesTextBtn")
        self.addExpensesTextBtn.setGeometry(QRect(330, 210, 100, 22))
        self.addExpensesTextBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesTextBtn.setAutoDefault(False)
        self.addExpensesFileBtn = QPushButton(self.centralwidget)
        self.addExpensesFileBtn.setObjectName(u"addExpensesFileBtn")
        self.addExpensesFileBtn.setEnabled(False)
        self.addExpensesFileBtn.setGeometry(QRect(10, 230, 150, 22))
        self.FoodLabel = QLabel(self.centralwidget)
        self.FoodLabel.setObjectName(u"FoodLabel")
        self.FoodLabel.setGeometry(QRect(170, 300, 60, 20))
        self.ExtraLabel = QLabel(self.centralwidget)
        self.ExtraLabel.setObjectName(u"ExtraLabel")
        self.ExtraLabel.setGeometry(QRect(610, 300, 70, 20))
        self.rightToolButton = QToolButton(self.centralwidget)
        self.rightToolButton.setObjectName(u"rightToolButton")
        self.rightToolButton.setGeometry(QRect(390, 400, 51, 20))
        self.rightToolButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolButton.setArrowType(Qt.ArrowType.RightArrow)
        self.leftToolButton = QToolButton(self.centralwidget)
        self.leftToolButton.setObjectName(u"leftToolButton")
        self.leftToolButton.setGeometry(QRect(390, 430, 51, 20))
        self.leftToolButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.leftToolButton.setArrowType(Qt.ArrowType.LeftArrow)
        self.ScrollAreaExpenses = QScrollArea(self.centralwidget)
        self.ScrollAreaExpenses.setObjectName(u"ScrollAreaExpenses")
        self.ScrollAreaExpenses.setGeometry(QRect(10, 330, 361, 191))
        self.ScrollAreaExpenses.setWidgetResizable(True)
        self.gridLayoutExpenses = QWidget()
        self.gridLayoutExpenses.setObjectName(u"gridLayoutExpenses")
        self.gridLayoutExpenses.setGeometry(QRect(0, 0, 359, 189))
        self.ScrollAreaExpenses.setWidget(self.gridLayoutExpenses)
        self.removeExpensesBtn = QPushButton(self.centralwidget)
        self.removeExpensesBtn.setObjectName(u"removeExpensesBtn")
        self.removeExpensesBtn.setGeometry(QRect(720, 530, 100, 22))
        self.removeExpensesBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.removeExpensesBtn.setAutoDefault(False)
        self.addExpensesToDBBtn = QPushButton(self.centralwidget)
        self.addExpensesToDBBtn.setObjectName(u"addExpensesToDBBtn")
        self.addExpensesToDBBtn.setGeometry(QRect(610, 530, 100, 22))
        self.addExpensesToDBBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesToDBBtn.setAutoDefault(False)
        self.ScrollAreaExtraExpenses = QScrollArea(self.centralwidget)
        self.ScrollAreaExtraExpenses.setObjectName(u"ScrollAreaExtraExpenses")
        self.ScrollAreaExtraExpenses.setGeometry(QRect(460, 330, 361, 191))
        self.ScrollAreaExtraExpenses.setWidgetResizable(True)
        self.gridLayoutExtraExpenses = QWidget()
        self.gridLayoutExtraExpenses.setObjectName(u"gridLayoutExtraExpenses")
        self.gridLayoutExtraExpenses.setGeometry(QRect(0, 0, 359, 189))
        self.ScrollAreaExtraExpenses.setWidget(self.gridLayoutExtraExpenses)
        self.chosenWeekLbl = QLabel(self.centralwidget)
        self.chosenWeekLbl.setObjectName(u"chosenWeekLbl")
        self.chosenWeekLbl.setGeometry(QRect(535, 270, 190, 22))
        self.chosenWeekLbl.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolSwitchWeek = QToolButton(self.centralwidget)
        self.rightToolSwitchWeek.setObjectName(u"rightToolSwitchWeek")
        self.rightToolSwitchWeek.setGeometry(QRect(735, 270, 20, 20))
        self.rightToolSwitchWeek.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolSwitchWeek.setArrowType(Qt.ArrowType.RightArrow)
        self.leftToolSwitchWeek = QToolButton(self.centralwidget)
        self.leftToolSwitchWeek.setObjectName(u"leftToolSwitchWeek")
        self.leftToolSwitchWeek.setGeometry(QRect(505, 270, 20, 20))
        self.leftToolSwitchWeek.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.leftToolSwitchWeek.setArrowType(Qt.ArrowType.LeftArrow)
        self.addExpensesToColumns = QPushButton(self.centralwidget)
        self.addExpensesToColumns.setObjectName(u"addExpensesToColumns")
        self.addExpensesToColumns.setGeometry(QRect(460, 530, 100, 22))
        self.addExpensesToColumns.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesToColumns.setAutoDefault(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 830, 20))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.paidOutThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0442\u0440\u0430\u0447\u0435\u043d\u043e \u043d\u0430 \u044d\u0442\u043e\u0439 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.remainedThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u0442\u0430\u043b\u043e\u0441\u044c \u043d\u0430 \u044d\u0442\u043e\u0439 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.paidOutThisWeekNum.setText("")
        self.remainedThisWeekNum.setText("")
        self.dateLabel.setText("")
        self.addExpensesLabel.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u044b \u0438\u0437 \u0442\u0435\u043a\u0441\u0442\u0430 ->", None))
        self.addExpensesTextBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.addExpensesFileBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u044b \u0438\u0437 \u0444\u0430\u0439\u043b\u0430", None))
        self.FoodLabel.setText(QCoreApplication.translate("MainWindow", u"\u0415\u0434\u0430", None))
        self.ExtraLabel.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043d\u0435\u0443\u0447\u0435\u0442\u043d\u044b\u0435", None))
        self.rightToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.leftToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.removeExpensesBtn.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.addExpensesToDBBtn.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043d\u0435\u0441\u0442\u0438 \u0442\u0440\u0430\u0442\u044b", None))
        self.chosenWeekLbl.setText("")
        self.rightToolSwitchWeek.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.leftToolSwitchWeek.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.addExpensesToColumns.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u0443", None))
    # retranslateUi

