# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QStatusBar, QTextEdit,
    QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(830, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.paidOutThisWeekLabel = QLabel(self.centralwidget)
        self.paidOutThisWeekLabel.setObjectName(u"paidOutThisWeekLabel")
        self.paidOutThisWeekLabel.setGeometry(QRect(450, 80, 180, 20))
        self.remainedThisWeekLabel = QLabel(self.centralwidget)
        self.remainedThisWeekLabel.setObjectName(u"remainedThisWeekLabel")
        self.remainedThisWeekLabel.setGeometry(QRect(450, 110, 180, 20))
        self.paidOutThisWeekNum = QLabel(self.centralwidget)
        self.paidOutThisWeekNum.setObjectName(u"paidOutThisWeekNum")
        self.paidOutThisWeekNum.setGeometry(QRect(630, 80, 50, 20))
        self.remainedThisWeekNum = QLabel(self.centralwidget)
        self.remainedThisWeekNum.setObjectName(u"remainedThisWeekNum")
        self.remainedThisWeekNum.setGeometry(QRect(630, 110, 50, 20))
        self.dateLabel = QLabel(self.centralwidget)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setGeometry(QRect(10, 20, 420, 50))
        font = QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.dateLabel.setFont(font)
        self.addExpensesTextEdit = QTextEdit(self.centralwidget)
        self.addExpensesTextEdit.setObjectName(u"addExpensesTextEdit")
        self.addExpensesTextEdit.setGeometry(QRect(190, 80, 240, 50))
        self.addExpensesTextEdit.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.IBeamCursor))
        self.addExpensesLabel = QLabel(self.centralwidget)
        self.addExpensesLabel.setObjectName(u"addExpensesLabel")
        self.addExpensesLabel.setGeometry(QRect(10, 80, 170, 20))
        self.addExpensesTextBtn = QPushButton(self.centralwidget)
        self.addExpensesTextBtn.setObjectName(u"addExpensesTextBtn")
        self.addExpensesTextBtn.setGeometry(QRect(330, 140, 100, 22))
        self.addExpensesTextBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesTextBtn.setAutoDefault(False)
        self.addExpensesFileBtn = QPushButton(self.centralwidget)
        self.addExpensesFileBtn.setObjectName(u"addExpensesFileBtn")
        self.addExpensesFileBtn.setEnabled(False)
        self.addExpensesFileBtn.setGeometry(QRect(10, 110, 170, 20))
        self.addExpensesFileBtn.setCheckable(False)
        self.FoodLabel = QLabel(self.centralwidget)
        self.FoodLabel.setObjectName(u"FoodLabel")
        self.FoodLabel.setGeometry(QRect(170, 300, 60, 20))
        self.ExtraLabel = QLabel(self.centralwidget)
        self.ExtraLabel.setObjectName(u"ExtraLabel")
        self.ExtraLabel.setGeometry(QRect(610, 300, 70, 20))
        self.rightToolButton = QToolButton(self.centralwidget)
        self.rightToolButton.setObjectName(u"rightToolButton")
        self.rightToolButton.setGeometry(QRect(390, 400, 50, 20))
        self.rightToolButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolButton.setArrowType(Qt.ArrowType.RightArrow)
        self.leftToolButton = QToolButton(self.centralwidget)
        self.leftToolButton.setObjectName(u"leftToolButton")
        self.leftToolButton.setGeometry(QRect(390, 430, 50, 20))
        self.leftToolButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.leftToolButton.setArrowType(Qt.ArrowType.LeftArrow)
        self.ScrollAreaExpenses = QScrollArea(self.centralwidget)
        self.ScrollAreaExpenses.setObjectName(u"ScrollAreaExpenses")
        self.ScrollAreaExpenses.setGeometry(QRect(10, 330, 360, 191))
        self.ScrollAreaExpenses.setWidgetResizable(True)
        self.gridLayoutExpenses = QWidget()
        self.gridLayoutExpenses.setObjectName(u"gridLayoutExpenses")
        self.gridLayoutExpenses.setGeometry(QRect(0, 0, 358, 189))
        self.ScrollAreaExpenses.setWidget(self.gridLayoutExpenses)
        self.removeExpensesBtn = QPushButton(self.centralwidget)
        self.removeExpensesBtn.setObjectName(u"removeExpensesBtn")
        self.removeExpensesBtn.setGeometry(QRect(720, 530, 100, 22))
        self.removeExpensesBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.removeExpensesBtn.setAutoDefault(False)
        self.addExpensesToDBBtn = QPushButton(self.centralwidget)
        self.addExpensesToDBBtn.setObjectName(u"addExpensesToDBBtn")
        self.addExpensesToDBBtn.setGeometry(QRect(610, 530, 100, 22))
        self.addExpensesToDBBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesToDBBtn.setAutoDefault(False)
        self.ScrollAreaExtraExpenses = QScrollArea(self.centralwidget)
        self.ScrollAreaExtraExpenses.setObjectName(u"ScrollAreaExtraExpenses")
        self.ScrollAreaExtraExpenses.setGeometry(QRect(460, 330, 360, 191))
        self.ScrollAreaExtraExpenses.setWidgetResizable(True)
        self.gridLayoutExtraExpenses = QWidget()
        self.gridLayoutExtraExpenses.setObjectName(u"gridLayoutExtraExpenses")
        self.gridLayoutExtraExpenses.setGeometry(QRect(0, 0, 358, 189))
        self.ScrollAreaExtraExpenses.setWidget(self.gridLayoutExtraExpenses)
        self.chosenWeekLbl = QLabel(self.centralwidget)
        self.chosenWeekLbl.setObjectName(u"chosenWeekLbl")
        self.chosenWeekLbl.setGeometry(QRect(480, 35, 200, 22))
        self.chosenWeekLbl.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolSwitchWeek = QToolButton(self.centralwidget)
        self.rightToolSwitchWeek.setObjectName(u"rightToolSwitchWeek")
        self.rightToolSwitchWeek.setGeometry(QRect(690, 35, 20, 20))
        self.rightToolSwitchWeek.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.rightToolSwitchWeek.setArrowType(Qt.ArrowType.RightArrow)
        self.leftToolSwitchWeek = QToolButton(self.centralwidget)
        self.leftToolSwitchWeek.setObjectName(u"leftToolSwitchWeek")
        self.leftToolSwitchWeek.setGeometry(QRect(450, 35, 20, 20))
        self.leftToolSwitchWeek.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.leftToolSwitchWeek.setArrowType(Qt.ArrowType.LeftArrow)
        self.addExpensesToColumns = QPushButton(self.centralwidget)
        self.addExpensesToColumns.setObjectName(u"addExpensesToColumns")
        self.addExpensesToColumns.setGeometry(QRect(340, 530, 150, 22))
        self.addExpensesToColumns.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.addExpensesToColumns.setAutoDefault(False)
        self.EUR_label = QLabel(self.centralwidget)
        self.EUR_label.setObjectName(u"EUR_label")
        self.EUR_label.setGeometry(QRect(730, 20, 30, 15))
        font1 = QFont()
        font1.setPointSize(9)
        self.EUR_label.setFont(font1)
        self.USD_label = QLabel(self.centralwidget)
        self.USD_label.setObjectName(u"USD_label")
        self.USD_label.setGeometry(QRect(730, 35, 30, 15))
        self.RUB_label = QLabel(self.centralwidget)
        self.RUB_label.setObjectName(u"RUB_label")
        self.RUB_label.setGeometry(QRect(730, 50, 30, 15))
        self.GEL_value_label = QLabel(self.centralwidget)
        self.GEL_value_label.setObjectName(u"GEL_value_label")
        self.GEL_value_label.setGeometry(QRect(760, 20, 70, 15))
        self.GEL_value_label.setFont(font1)
        self.USD_value_label = QLabel(self.centralwidget)
        self.USD_value_label.setObjectName(u"USD_value_label")
        self.USD_value_label.setGeometry(QRect(760, 35, 70, 15))
        self.USD_value_label.setFont(font1)
        self.RUB_value_label = QLabel(self.centralwidget)
        self.RUB_value_label.setObjectName(u"RUB_value_label")
        self.RUB_value_label.setGeometry(QRect(760, 50, 70, 15))
        self.RUB_value_label.setFont(font1)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(440, 20, 3, 50))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.unfixExpensesThisWeekNum = QLabel(self.centralwidget)
        self.unfixExpensesThisWeekNum.setObjectName(u"unfixExpensesThisWeekNum")
        self.unfixExpensesThisWeekNum.setGeometry(QRect(630, 140, 50, 20))
        self.unfixExpensesThisWeekLabel = QLabel(self.centralwidget)
        self.unfixExpensesThisWeekLabel.setObjectName(u"unfixExpensesThisWeekLabel")
        self.unfixExpensesThisWeekLabel.setGeometry(QRect(450, 140, 180, 20))
        self.lizaExpensesThisWeekLabel = QLabel(self.centralwidget)
        self.lizaExpensesThisWeekLabel.setObjectName(u"lizaExpensesThisWeekLabel")
        self.lizaExpensesThisWeekLabel.setGeometry(QRect(450, 170, 180, 20))
        self.lizaExpensesThisWeekNum = QLabel(self.centralwidget)
        self.lizaExpensesThisWeekNum.setObjectName(u"lizaExpensesThisWeekNum")
        self.lizaExpensesThisWeekNum.setGeometry(QRect(630, 170, 50, 20))
        self.ExpensesThisMonthLabel = QLabel(self.centralwidget)
        self.ExpensesThisMonthLabel.setObjectName(u"ExpensesThisMonthLabel")
        self.ExpensesThisMonthLabel.setGeometry(QRect(450, 200, 180, 20))
        self.ExpensesThisMonthNum = QLabel(self.centralwidget)
        self.ExpensesThisMonthNum.setObjectName(u"ExpensesThisMonthNum")
        self.ExpensesThisMonthNum.setGeometry(QRect(630, 200, 181, 45))
        self.monthDatesLabel = QLabel(self.centralwidget)
        self.monthDatesLabel.setObjectName(u"monthDatesLabel")
        self.monthDatesLabel.setGeometry(QRect(450, 220, 180, 11))
        font2 = QFont()
        font2.setPointSize(8)
        font2.setItalic(True)
        self.monthDatesLabel.setFont(font2)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(627, 250, 191, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.ExpensesThisMonthLabel_2 = QLabel(self.centralwidget)
        self.ExpensesThisMonthLabel_2.setObjectName(u"ExpensesThisMonthLabel_2")
        self.ExpensesThisMonthLabel_2.setGeometry(QRect(590, 260, 41, 20))
        self.ExpensesThisMonthNumOverall = QLabel(self.centralwidget)
        self.ExpensesThisMonthNumOverall.setObjectName(u"ExpensesThisMonthNumOverall")
        self.ExpensesThisMonthNumOverall.setGeometry(QRect(630, 260, 191, 20))
        self.monthlyRentLbl = QLabel(self.centralwidget)
        self.monthlyRentLbl.setObjectName(u"monthlyRentLbl")
        self.monthlyRentLbl.setGeometry(QRect(10, 150, 95, 20))
        self.monthlyRentNum = QLineEdit(self.centralwidget)
        self.monthlyRentNum.setObjectName(u"monthlyRentNum")
        self.monthlyRentNum.setGeometry(QRect(110, 150, 50, 20))
        self.monthlyRentCurrencyComboBox = QComboBox(self.centralwidget)
        self.monthlyRentCurrencyComboBox.addItem("")
        self.monthlyRentCurrencyComboBox.addItem("")
        self.monthlyRentCurrencyComboBox.setObjectName(u"monthlyRentCurrencyComboBox")
        self.monthlyRentCurrencyComboBox.setGeometry(QRect(170, 150, 60, 20))
        self.remainDebtNum = QLineEdit(self.centralwidget)
        self.remainDebtNum.setObjectName(u"remainDebtNum")
        self.remainDebtNum.setGeometry(QRect(110, 180, 121, 20))
        self.remainDebtLbl = QLabel(self.centralwidget)
        self.remainDebtLbl.setObjectName(u"remainDebtLbl")
        self.remainDebtLbl.setGeometry(QRect(10, 180, 95, 20))
        self.calcDebtBtn = QPushButton(self.centralwidget)
        self.calcDebtBtn.setObjectName(u"calcDebtBtn")
        self.calcDebtBtn.setGeometry(QRect(240, 180, 100, 22))
        self.calcDebtBtn.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.calcDebtBtn.setAutoDefault(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 830, 20))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.paidOutThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0442\u0440\u0430\u0447\u0435\u043d\u043e \u043d\u0430 \u044d\u0442\u043e\u0439 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.remainedThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u0442\u0430\u043b\u043e\u0441\u044c \u043d\u0430 \u044d\u0442\u043e\u0439 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.paidOutThisWeekNum.setText("")
        self.remainedThisWeekNum.setText("")
        self.dateLabel.setText("")
        self.addExpensesLabel.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u044b \u0438\u0437 \u0442\u0435\u043a\u0441\u0442\u0430 ->", None))
        self.addExpensesTextBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.addExpensesFileBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u044b \u0438\u0437 \u0444\u0430\u0439\u043b\u0430", None))
        self.FoodLabel.setText(QCoreApplication.translate("MainWindow", u"\u0415\u0434\u0430", None))
        self.ExtraLabel.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043d\u0435\u0443\u0447\u0435\u0442\u043d\u044b\u0435", None))
        self.rightToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.leftToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.removeExpensesBtn.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.addExpensesToDBBtn.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u0440\u0430\u0442\u0443", None))
        self.chosenWeekLbl.setText("")
        self.rightToolSwitchWeek.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.leftToolSwitchWeek.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.addExpensesToColumns.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043d\u0435\u0441\u0442\u0438 \u0442\u0440\u0430\u0442\u044b \u0432 \u0431\u0430\u0437\u0443", None))
        self.EUR_label.setText(QCoreApplication.translate("MainWindow", u"GEL:", None))
        self.USD_label.setText(QCoreApplication.translate("MainWindow", u"USD:", None))
        self.RUB_label.setText(QCoreApplication.translate("MainWindow", u"RUB:", None))
        self.GEL_value_label.setText("")
        self.USD_value_label.setText("")
        self.RUB_value_label.setText("")
        self.unfixExpensesThisWeekNum.setText("")
        self.unfixExpensesThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043d\u0435\u0443\u0447\u0435\u0442\u043d\u044b\u0435 \u0442\u0440\u0430\u0442\u044b \u043d\u0430 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.lizaExpensesThisWeekLabel.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0440\u0430\u0442\u044b \u041b\u0438\u0437\u043e\u0447\u043a\u0438 \u043d\u0430 \u043d\u0435\u0434\u0435\u043b\u0435:", None))
        self.lizaExpensesThisWeekNum.setText("")
        self.ExpensesThisMonthLabel.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e \u0437\u0430 \u043c\u0435\u0441\u044f\u0446:", None))
        self.ExpensesThisMonthNum.setText("")
        self.monthDatesLabel.setText("")
        self.ExpensesThisMonthLabel_2.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e:", None))
        self.ExpensesThisMonthNumOverall.setText("")
        self.monthlyRentLbl.setText(QCoreApplication.translate("MainWindow", u"\u0410\u0440\u0435\u043d\u0434\u043d\u0430\u044f \u043f\u043b\u0430\u0442\u0430:", None))
        self.monthlyRentNum.setText(QCoreApplication.translate("MainWindow", u"600", None))
        self.monthlyRentCurrencyComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"USD", None))
        self.monthlyRentCurrencyComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"EUR", None))

        self.remainDebtNum.setText(QCoreApplication.translate("MainWindow", u"-3704.13", None))
        self.remainDebtLbl.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0441\u0442\u0430\u0432\u0448\u0438\u0439\u0441\u044f \u0434\u043e\u043b\u0433:", None))
        self.calcDebtBtn.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0441\u0441\u0447\u0438\u0442\u0430\u0442\u044c", None))
    # retranslateUi

